name: VirtualHere Client Mounter
slug: virtualhereclient
startup: services
url: https://github.com/lexiismadd/hassio-virtualhere-mounter
panel_icon: mdi:usb
usbip: true
usb: true
kernel_modules: true
host_network: true
apparmor: false
version: 1.2.0
description: VirtualHere Client USB over IP Client Handler to attach USB devices from a VirtualHere server instance to HAOS
image: lexiismadd/hassio-{arch}-virtualhere-mounter
init: false
full_access: true
arch:
- amd64
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
devices:
  - /dev/mem
schema:
  devices:
    - server_address: str
      bus_id: int
options:
  devices: []
